name: test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install Vapor      
      run: brew cask install vapor && brew install vapor
    - uses: actions/checkout@v2 
    - name: Build
      run: vapor build -v
    - name: Run tests
      run: vapor test -v
