name: test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - run: xcrun swift test --enable-test-discovery --sanitize=thread
