name: test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Vapor
      run: |
        homebrew install vapor
    - name: Build
      run: vapor build -v
    - name: Run tests
      run: vapor test -v
