name: test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libssl-dev
      run: sudo apt-get install libssl-dev      
    - name: Run Tests
      run: swift test --enable-test-discovery --sanitize=thread
  
